# Generated by Django 4.2.30 on 2026-05-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('telegram_username', models.CharField(blank=True, help_text='Без символа @, например: alibek_taxi', max_length=100, null=True, verbose_name='Telegram (@username)')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Марка машины')),
                ('car_color', models.CharField(blank=True, max_length=50, verbose_name='Цвет машины')),
                ('car_plate', models.CharField(blank=True, max_length=20, verbose_name='Гос. номер')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='Поездок всего')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Таксист',
                'verbose_name_plural': 'Таксисты',
                'ordering': ['-rating', '-total_rides'],
            },
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=150, verbose_name='Откуда (город/район)')),
                ('to_district', models.CharField(max_length=150, verbose_name='Куда (посёлок/район)')),
                ('route_description', models.TextField(blank=True, help_text='Доп. информация: заезды, промежуточные остановки и т.д.', verbose_name='Описание маршрута')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('price_per_seat', models.PositiveIntegerField(verbose_name='Цена за место (сум)')),
                ('seats_available', models.PositiveSmallIntegerField(default=3, verbose_name='Свободных мест')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('booked', 'Забронировано'), ('done', 'Завершено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.driver', verbose_name='Таксист')),
            ],
            options={
                'verbose_name': 'Объявление о поездке',
                'verbose_name_plural': 'Объявления о поездках',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Имя пассажира')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='Телефон пассажира')),
                ('seats_requested', models.PositiveSmallIntegerField(default=1, verbose_name='Запрошено мест')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий пассажира')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rides.rideoffer', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
