# Generated by Django 6.0.5 on 2026-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='driver',
            name='card_number',
            field=models.CharField(blank=True, help_text='Только цифры, например: 8600123412341234', max_length=20, null=True, verbose_name='Номер карты (Humo/Uzcard)'),
        ),
    ]
